# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Better Terraform Practices
email: zack.higdon@gmail.com
description: >- 
  Better Terraform Practices Documentation
baseurl: "" # the subpath of your site, should match repository name
url: "https://betterterraformpractices.com" # replace with your GitHub username
github_username: Zigdon7

# Build settings
theme: just-the-docs
color_scheme: dark

# ... rest of your existing config ...
aux_links:
  "View on GitHub":
    - "https://github.com/Zigdon7/betterterraformpractices"

# Navigation
nav:
  enabled: true
  levels: 3

# Search
search:
  enabled: true
  heading_level: 3
permalink: pretty
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
  enable_nav_level_1: true
  enable_nav_level_2: true
  enable_nav_level_3: true

gh_edit_link: false  # Disable "Edit this page on GitHub" link
back_to_top: true    # Keep the back to top link if you want it
back_to_top_text: "Back to top" # Customize back to top text
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
